### ISSUE TITLE
For tests where is picolisp repl?

### ISSUE THREAD

**Issue by borgauf** [tj64/ob-picolisp#4]
I've cloned this, set it up with my Emacs and have opened ob-picolisp-tests.org and ran the first code block (C-c C-c) and, voila, I get a result. But where is the picolisp REPL that is supposedly handling this? I'm used to having a REPL start (in the case of Racket with Geiser) whenever I run the first Racket Scheme code block of an org buffer. How do I get a picolisp REPL to be associated with an org file buffer containing picolisp blocks? I'm on Emacs 25.3.1 and org-mode 9.1.6.

**Comment by tj64** [comment]
Hello, see my answers on both the org-mode and the picolisp mailing list.
You need an src-block with a session.
